/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package autonoma.AventuraMagicaGame.ui;

import autonoma.AventuraMagicaGame.elements.Nivel;
import autonoma.AventuraMagicaGame.elements.NivelBase;
import autonoma.AventuraMagicaGame.elements.NivelFacil;
import autonoma.AventuraMagicaGame.util.GestorNivel;
import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author jgiugtiñut
 */
public class Ventana extends javax.swing.JFrame {
 private PanelJuego panelJuego;

    /**
     * Creates new form Ventana
     */
    public Ventana(NivelBase nivelBase) {
        initComponents();

        setSize(800, 600);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);

        // NO creamos ni ponemos el panelJuego todavía
        // Así que el botón sigue visible al iniciar
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIniciarJuego = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnIniciarJuego.setText("jButton1");
        btnIniciarJuego.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIniciarJuegoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(307, Short.MAX_VALUE)
                .addComponent(btnIniciarJuego)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addComponent(btnIniciarJuego)
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarJuegoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarJuegoMouseClicked
        try {
            GestorNivel gestor = new GestorNivel();
            Nivel nivelActual = gestor.getNivelActual();

            panelJuego = new PanelJuego((NivelBase) nivelActual);
            panelJuego.setPreferredSize(new Dimension(800, 600));

            // Reemplazamos todo el contenido actual (el botón) por el panelJuego
            getContentPane().removeAll();
            setLayout(new BorderLayout());
            add(panelJuego, BorderLayout.CENTER);

            revalidate();
            repaint();

            panelJuego.requestFocusInWindow();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al iniciar el juego: " + e.getMessage());
        }


    }//GEN-LAST:event_btnIniciarJuegoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarJuego;
    // End of variables declaration//GEN-END:variables
}
